import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const HARNESS_DIR = join(homedir(), '.forgeclaw', 'harness');

/**
 * Ordered list of harness files to compile into CLAUDE.md.
 * Order matters: SOUL defines identity, USER adds personal context,
 * AGENTS/TOOLS/MEMORY provide capabilities, STYLE sets output format.
 */
const HARNESS_FILES = [
  'SOUL.md',
  'USER.md',
  'AGENTS.md',
  'TOOLS.md',
  'MEMORY.md',
  'STYLE.md',
] as const;

export interface CompileHarnessResult {
  success: boolean;
  outputPath: string;
  includedFiles: string[];
  missingFiles: string[];
}

/**
 * Compile individual harness files into a single CLAUDE.md.
 *
 * Reads each file in HARNESS_FILES order, concatenates with section
 * headers, writes to ~/.forgeclaw/harness/CLAUDE.md.
 *
 * Missing files are skipped (logged in result.missingFiles).
 * At least one file must exist for compilation to succeed.
 *
 * @param harnessDir - Override harness directory (for testing). Defaults to ~/.forgeclaw/harness/
 * @returns CompileHarnessResult with success status and file lists
 */
export function compileHarness(harnessDir?: string): CompileHarnessResult {
  const dir = harnessDir ?? HARNESS_DIR;
  const outputPath = join(dir, 'CLAUDE.md');
  const includedFiles: string[] = [];
  const missingFiles: string[] = [];
  const sections: string[] = [];

  // Header
  sections.push('<!-- AUTO-GENERATED by compileHarness() — do not edit manually -->');
  sections.push('<!-- Edit individual files (SOUL.md, USER.md, etc.) and recompile -->');
  sections.push('');

  for (const fileName of HARNESS_FILES) {
    const filePath = join(dir, fileName);

    if (!existsSync(filePath)) {
      missingFiles.push(fileName);
      console.warn(`[harness-compiler] Skipping ${fileName} (not found)`);
      continue;
    }

    try {
      const content = readFileSync(filePath, 'utf-8').trim();
      if (content.length === 0) {
        missingFiles.push(fileName);
        console.warn(`[harness-compiler] Skipping ${fileName} (empty)`);
        continue;
      }

      // Section separator with file name for debugging
      sections.push(`<!-- === ${fileName} === -->`);
      sections.push(content);
      sections.push('');
      includedFiles.push(fileName);
    } catch (err) {
      missingFiles.push(fileName);
      console.error(`[harness-compiler] Error reading ${fileName}:`, err);
    }
  }

  if (includedFiles.length === 0) {
    console.error('[harness-compiler] No harness files found. CLAUDE.md not generated.');
    return { success: false, outputPath, includedFiles, missingFiles };
  }

  const compiled = sections.join('\n');
  writeFileSync(outputPath, compiled);
  console.log(`[harness-compiler] CLAUDE.md compiled from ${includedFiles.length} files (${compiled.length} bytes)`);

  return { success: true, outputPath, includedFiles, missingFiles };
}

/**
 * Check if the compiled CLAUDE.md exists and is non-empty.
 */
export function isHarnessCompiled(harnessDir?: string): boolean {
  const dir = harnessDir ?? HARNESS_DIR;
  const outputPath = join(dir, 'CLAUDE.md');

  if (!existsSync(outputPath)) return false;

  try {
    const content = readFileSync(outputPath, 'utf-8');
    return content.trim().length > 0;
  } catch {
    return false;
  }
}
