interface UserInfo {
  name: string
  company: string
  role: string
}

export function userTemplate(info: UserInfo): string {
  return `# USER.md - User Profile

## Identity

- **Name:** ${info.name}
- **Company:** ${info.company || 'Not specified'}
- **Role:** ${info.role || 'Not specified'}

## Preferences

- Preferred language: Portuguese (Brazil)
- Communication style: Direct and concise
- Code style: Follow project conventions

## Context

This file is auto-generated by ForgeClaw installer.
Update it to customize how ForgeClaw interacts with you.

## Working Hours

- Available: Flexible
- Timezone: Auto-detected

## Notification Preferences

- Critical alerts: Always
- Task completions: During working hours
- Daily summaries: Morning
`
}
